source("getData.R")
electricData <- getData()
dateTime <- strptime(paste(electricData$Date,electricData$Time),format = "%d/%m/%Y %H:%M:%S")
globalActivePower <- as.numeric(electricData$Global_active_power)
subMetering1 <- as.numeric(electricData$Sub_metering_1)
subMetering2 <- as.numeric(electricData$Sub_metering_2)
subMetering3 <- as.numeric(electricData$Sub_metering_3)
voltage <- as.numeric(electricData$Voltage)
globalRelactivePower <- as.numeric(electricData$Global_reactive_power)
png(filename = "plot4.png")
par(mfcol=c(2,2))
plot(dateTime,globalActivePower,type = "l",ylab="Global Active Power(kilwatts)")
plot(dateTime,subMetering1,type = "l",ylab = "Energy sub metering")
lines(dateTime,y = subMetering2,col= "red")
lines(dateTime,y = subMetering3,col= "blue")
legend("topright",legend = c("subMetering1","subMetering2","subMetering1"),fill = c("black","red","blue"))
plot(dateTime,voltage,type = "l",ylab = "Voltage")
plot(dateTime,globalRelactivePower,type = "l")
graphics.off()
